name: CI Quality Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-analysis:
    name: Backend Quality (Spring Boot)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # allows sonar to compare versions

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd backend/IRBoard-backend
          ./mvnw verify sonar:sonar \
            -Dsonar.projectKey=Y4vra_IRBoard_Backend \
            -Dsonar.organization=y4vra \
            -Dsonar.host.url=https://sonarcloud.io

  frontend-analysis:
    name: Frontend Quality (React)
    runs-on: ubuntu-latest
    # Only executes if a change happens on frontend
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      # Placeholder, poner los comandos de npm install, test y el scanner de Sonar para JS